# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deploy
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  DeployArtifacts:
    name: Deploy artifacts to Maven Central
    if: github.ref == 'refs/heads/release'
    needs: [BuildAndTest]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Java 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
          server-id: central                              # must match the serverId configured for the nexus-staging-maven-plugin
          server-username: MAVEN_USERNAME                 # Env var that holds the central publisher user name
          server-password: MAVEN_CENTRAL_TOKEN            # Env var that holds the central publisher user token
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Substituted with the value stored in the referenced secret
          gpg-passphrase: MAVEN_GPG_PASSPHRASE            # Env var that holds the key's passphrase
      - name: Deploy Axml
        run: mvn -B -U clean deploy -P deploy -DskipTests -Dcheckstyle.failOnViolation=true
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
